on: [push, pull_request]
name: checks

jobs:
  test:
    name: ${{ matrix.std }} / ${{ matrix.backend }} / ${{ matrix.serde }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        std: [std, no_std]
        backend: [pure_rust, ring]
        serde: [serde, no-serde]
        exclude:
          # ring requires std
          - std: no_std
            backend: ring
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Test
        run: |
          features="${{ matrix.backend }}"
          if [ "${{ matrix.std }}" = "std" ]; then
            features="std ${features}"
          fi
          if [ "${{ matrix.serde }}" = "serde" ]; then
            features="${features} serde"
          fi
          cargo test --no-default-features --features "${features}"

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt
      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: clippy
      - name: Clippy Check
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  no_std:
    name: no_std / ${{ matrix.serde }} / thumbv7em-none-eabi
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        serde: [serde, no-serde]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv7em-none-eabi
          profile: minimal
          override: true
      - name: Build
        run: |
          features="pure_rust"
          if [ "${{ matrix.serde }}" = "serde" ]; then
            features="${features} serde"
          fi
          cargo build --no-default-features --features "${features}" --target thumbv7em-none-eabi

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run cargo-tarpaulin (ring feature)
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: "--ignore-tests  --no-default-features --features=std,ring,serde"
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: "--ignore-tests  --no-default-features --features=pure_rust,serde"
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
