on: [push, pull_request]
name: checks

jobs:
  test:
    name: ${{ matrix.std }} / ${{ matrix.serde }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        std: [std, no_std]
        serde: [serde, no-serde]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Test
        run: |
          features=""
          if [ "${{ matrix.std }}" = "std" ]; then
            features="std"
          fi
          if [ "${{ matrix.serde }}" = "serde" ]; then
            features="${features} serde"
          fi
          cargo test --no-default-features --features "${features}"

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt
      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: clippy
      - name: Clippy Check
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  no_std:
    name: no_std / ${{ matrix.serde }} / thumbv7em-none-eabi
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        serde: [serde, no-serde]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv7em-none-eabi
          profile: minimal
          override: true
      - name: Build
        run: |
          features=""
          if [ "${{ matrix.serde }}" = "serde" ]; then
            features="serde"
          fi
          cargo build --no-default-features --features "${features}" --target thumbv7em-none-eabi

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-tarpaulin
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-tarpaulin
      - name: Run cargo-tarpaulin
        run: cargo tarpaulin --ignore-tests --out Xml --features=serde
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Run cargo-tarpaulin (no_std)
        run: cargo tarpaulin --ignore-tests --out Xml --no-default-features --features=serde
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
